SCCXF = \
stop.f \
stopwithout201.f \
closefile.f \
openfile.f \
readinput.f \
includefilename.f \
keystart.f \
splitline.f \
restartshort.f \
skip.f \
allocation.f \
inputerror.f \
getnewline.f \
userelements.f \
nidentk.f \
betacalinput.f


SCCXC = \
strcmp1.c \
strcmp2.c \
strcpy1.c \
u_calloc.c \
u_realloc.c \
readinput.c \
u_free.c \


SCCXCXX = umat_dl.cpp